#!/bin/bash

# BE CAREFUL - this scrubs you whole system's Docker files
# docker system prune --volumes -a

[ -n "$2" ] && appName=$2 || appName="vue-lorenz"

case $1 in
'run')
    docker run -it --rm --network="host" \
        --volume $HOME:/home/dev \
        --name running-$appName $appName \
        sh -c "useradd -m -u $(id -u) dev -s /bin/bash ; exec su dev"
    ;;
'shell')
    docker container exec -it running-$appName bash
    ;;
'build')
    docker build -t $appName ./docker
    ;;
*)
    echo "./docker/container [run|shell|build] app-name"
    ;;
esac

