#!/bin/bash

# TODO: Provide a less "brutal" method for clearing out containers
#
# BE CAREFUL - this scrubs you whole system's Docker files
#
# docker system prune --volumes -a

[ -n "$2" ] && appName=$2 || appName="vue-lorenz"

case $1 in
'run')
    docker run \
        --rm \
        --interactive --tty \
        --publish 80:9000 \
        --volume $(pwd):/usr/local/src \
        --volume $HOME/.ssh:/root/.ssh \
        --name running-$appName $appName
    ;;
'shell')
    docker container exec -it running-$appName bash
    ;;
'build')
    docker build -t $appName ./docker
    ;;
*)
    echo "./docker/container [run|shell|build] app-name"
    ;;
esac

