#!/bin/bash

# TODO: Provide a less "brutal" method for clearing out containers
#
# BE CAREFUL - this scrubs you whole system's Docker files
#
# docker system prune --volumes -a

[ -n "$2" ] && appName=$2 || appName="vue-lorenz"

case $1 in
'run')
    # user `dev` inside the container is "the current user" outside.
    # For the benefit of the bind mount
    USER_ADD="useradd -m -u $(id -u) dev -s /bin/bash"
    OWN_DIR="chown dev /home/dev /home/dev/.ssh"
    # TODO: The `exec su dev` can result in the container terminating
    # on SOME error states conditions.
    docker run -it --rm --network="host" \
        --volume $(pwd):/usr/local/src \
        --volume $HOME/.ssh:/home/dev/.ssh \
        --name running-$appName $appName \
        sh -c "$USER_ADD ; $OWN_DIR ; exec su dev"
    ;;
'shell')
    docker container exec -it running-$appName bash
    ;;
'build')
    docker build -t $appName ./docker
    ;;
*)
    echo "./docker/container [run|shell|build] app-name"
    ;;
esac

